/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.carlmontrobotics.commandvisualizer.client;

import java.io.IOException;

import javax.swing.SwingUtilities;

import edu.wpi.first.cscore.CameraServerJNI;
import edu.wpi.first.math.WPIMathJNI;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.NetworkTablesJNI;
import edu.wpi.first.util.CombinedRuntimeLoader;
import edu.wpi.first.util.WPIUtilJNI;

public class App {

    public static void main(String[] args) throws IOException { // See: https://docs.wpilib.org/en/stable/docs/software/networktables/client-side-program.html
        NetworkTablesJNI.Helper.setExtractOnStaticLoad(false);
        WPIUtilJNI.Helper.setExtractOnStaticLoad(false);
        WPIMathJNI.Helper.setExtractOnStaticLoad(false);
        CameraServerJNI.Helper.setExtractOnStaticLoad(false);

        CombinedRuntimeLoader.loadLibraries(App.class, "wpiutiljni", "wpimathjni", "ntcorejni",
                "cscorejnicvstatic");

        // NetworkTableInstance.getDefault().startDSClient(); // TODO: Maybe add a GUI or a better way to specify how to connect
        NetworkTableInstance.getDefault().setServer("localhost");
        NetworkTableInstance.getDefault().startClient4("CommmandVisualizer");

        SwingUtilities.invokeLater(GUI::new);
    }

}
